# Generated by Django 5.1.5 on 2026-09-08 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'Instant UPI / QR / Google Pay / PhonePe'), ('Card', 'Luxury Black / Metal / Credit & Debit Card'), ('NetBanking', 'Priority Net Banking (HDFC, ICICI, SBI, Axis)'), ('Vault_COD', 'VIP Insured Cash on Delivery (Assisted Inspection)')], default='UPI', max_length=30)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid & Verified'), ('Pending', 'Payment Pending / On Delivery'), ('Failed', 'Payment Failed')], default='Paid', max_length=30)),
                ('order_status', models.CharField(choices=[('Confirmed', 'Order Placed & Confirmed'), ('Processing', 'Crafting & Gemological Inspection'), ('Dispatched', 'Dispatched via Insured High-Value Armored Courier'), ('Out for Delivery', 'Out for White-Glove Delivery'), ('Delivered', 'Delivered to Customer'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=40)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_gst', models.DecimalField(decimal_places=2, default=0, help_text='3% Fine Jewellery GST', max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coupon_code', models.CharField(blank=True, max_length=40)),
                ('gift_message', models.TextField(blank=True, help_text='Complimentary Celestial Hand-Written Calligraphy Note')),
                ('special_instructions', models.TextField(blank=True)),
                ('tracking_number', models.CharField(blank=True, default='AJ-SECURE-EXP-77291', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Luxury Order',
                'verbose_name_plural': 'Luxury Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_sku', models.CharField(max_length=60)),
                ('product_image_url', models.CharField(blank=True, max_length=500)),
                ('selected_size', models.CharField(default='Standard', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
