# Generated by Django 5.1.5 on 2026-09-08 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='+91 98765 43210', max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2 (Apartment, Suite)')),
                ('landmark', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, default='Mumbai', max_length=100)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Delhi', 'Delhi NCR'), ('Gujarat', 'Gujarat'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Rajasthan', 'Rajasthan'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal'), ('Other', 'Other State/UT')], default='Maharashtra', max_length=100)),
                ('pincode', models.CharField(blank=True, default='400001', max_length=10)),
                ('vip_tier', models.CharField(choices=[('Member', 'Aether Member'), ('Silver Astral', 'Silver Astral'), ('Gold Celestial', 'Gold Celestial'), ('Solitaire Platinum', 'Solitaire Platinum VIP')], default='Member', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
