# Generated by Django 5.1.5 on 2026-09-08 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('image_url', models.CharField(blank=True, max_length=600)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jewellery Category',
                'verbose_name_plural': 'Jewellery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('sku', models.CharField(help_text='e.g. AJ-RNG-01', max_length=50, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='e.g. Celestial Constellation in 18K Gold', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR (₹)', max_digits=12)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original MRP before discount in INR (₹)', max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(default=5)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('short_description', models.TextField(help_text='Summary for cards and fast overview')),
                ('description', models.TextField(help_text='Detailed craftsmanship narrative')),
                ('metal_karat', models.CharField(choices=[('18K Yellow Gold', '18K Yellow Gold'), ('18K Rose Gold', '18K Rose Gold'), ('18K White Gold', '18K White Gold'), ('22K Royal Gold', '22K Royal Gold'), ('950 Pure Platinum', '950 Pure Platinum'), ('Dual Tone 18K Gold', 'Dual Tone 18K Gold & Platinum')], default='18K Yellow Gold', max_length=60)),
                ('metal_weight_grams', models.DecimalField(decimal_places=2, default=5.5, help_text='Gross weight in grams', max_digits=6)),
                ('gemstone_type', models.CharField(choices=[('Natural Diamond', 'Solitaire & Natural Diamond'), ('Zambian Emerald', 'Royal Zambian Emerald'), ('Ceylon Sapphire', 'Kashmir/Ceylon Blue Sapphire'), ('Burmese Ruby', 'Pigeon Blood Burmese Ruby'), ('Tanzanite & Diamond', 'Celestial Tanzanite & Diamond'), ('South Sea Pearl', 'Lustrous South Sea Pearl'), ('Moissanite VVS', 'Celestial Moissanite & Diamond')], default='Natural Diamond', max_length=80)),
                ('diamond_carat', models.DecimalField(blank=True, decimal_places=2, help_text='Diamond total weight in carats', max_digits=5, null=True)),
                ('diamond_clarity', models.CharField(blank=True, default='VVS1 - IF', max_length=50)),
                ('diamond_cut', models.CharField(blank=True, default='Ideal Round Brilliant', max_length=50)),
                ('certification', models.CharField(default='100% BIS Hallmarked & IGI / SGL Certified', max_length=150)),
                ('dimensions', models.CharField(blank=True, default='Standard Luxury Proportion', max_length=100)),
                ('size_options', models.CharField(blank=True, default='6,7,8,9,10,12,14', help_text='Comma-separated ring/bangle sizes', max_length=100)),
                ('image_url', models.CharField(help_text='Primary High-Res Product Image URL', max_length=600)),
                ('image_url_2', models.CharField(blank=True, help_text='Angle 2 / Model view', max_length=600)),
                ('image_url_3', models.CharField(blank=True, help_text='Angle 3 / Macro gemstone view', max_length=600)),
                ('image_url_4', models.CharField(blank=True, help_text='Angle 4 / Luxury packaging view', max_length=600)),
                ('rating', models.DecimalField(decimal_places=2, default=4.9, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'verbose_name': 'Fine Jewellery Piece',
                'verbose_name_plural': 'Fine Jewellery Pieces',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('title', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('verified_purchase', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
