# Generated by Django 5.1.5 on 2026-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('metal_preference', models.CharField(default='18K Yellow / White Gold', max_length=100)),
                ('gemstone_preference', models.CharField(default='Certified Natural Diamonds', max_length=100)),
                ('budget_estimate', models.CharField(default='₹3,00,000+', max_length=100)),
                ('design_idea', models.TextField(help_text='Describe your dream piece or celestial concept')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bespoke Design Commission',
                'verbose_name_plural': 'Bespoke Design Commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='+91 98765 43210', max_length=20)),
                ('consultation_type', models.CharField(choices=[('Virtual VIP', 'Virtual High-Definition VIP Video Consultation'), ('Mumbai Flagship', 'Mumbai Flagship Atelier (Bandra West)'), ('Delhi Boutique', 'Delhi DLF Emporio Luxury Salon'), ('Bengaluru Lounge', 'Bengaluru UB City Private Suite'), ('Jaipur Heritage', 'Jaipur Sovereign Heritage Salon')], default='Virtual VIP', max_length=50)),
                ('preferred_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('11:00 AM - 01:00 PM', 'Morning Salon (11:00 AM - 01:00 PM)'), ('02:00 PM - 04:00 PM', 'Afternoon Soirée (02:00 PM - 04:00 PM)'), ('04:30 PM - 06:30 PM', 'Sunset Viewing (04:30 PM - 06:30 PM)'), ('07:00 PM - 09:00 PM', 'Private Evening Suite (07:00 PM - 09:00 PM)')], default='02:00 PM - 04:00 PM', max_length=60)),
                ('interest_category', models.CharField(choices=[('Solitaires', 'Celestial High Solitaires & Engagement'), ('Bridal', 'Royal Bridal Sets & Astral Necklaces'), ('Bespoke', 'Bespoke Haute Joaillerie Commission'), ('Talismans', 'Zodiac & Planetary Talismans'), ('Everyday Fine', 'Minimalist Starlight & Solar Everyday Luxury')], default='Solitaires', max_length=50)),
                ('budget_range', models.CharField(choices=[('₹1,00,000 - ₹3,00,000', '₹1,00,000 - ₹3,00,000'), ('₹3,00,000 - ₹7,50,000', '₹3,00,000 - ₹7,50,000'), ('₹7,50,000 - ₹15,00,000', '₹7,50,000 - ₹15,00,000'), ('₹15,00,000+ Sovereign', '₹15,00,000+ Sovereign Haute Joaillerie')], default='₹3,00,000 - ₹7,50,000', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Specific requirements, ring sizes, or gemstone preferences')),
                ('status', models.CharField(choices=[('Pending', 'Pending Concierge Confirmation'), ('Confirmed', 'Confirmed with Personal Gemologist'), ('Completed', 'Consultation Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VIP Consultation Booking',
                'verbose_name_plural': 'VIP Consultation Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
