# Generated by Django 5.1.5 on 2026-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokeinquiry',
            name='carat_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=4.5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeinquiry',
            name='custom_engraving',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bespokeinquiry',
            name='estimated_price_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bespokeinquiry',
            name='piece_type',
            field=models.CharField(blank=True, default='Solitaire Ring', max_length=100),
        ),
        migrations.AddField(
            model_name='bespokeinquiry',
            name='setting_style',
            field=models.CharField(blank=True, default='Astral Halo', max_length=100),
        ),
        migrations.AlterField(
            model_name='bespokeinquiry',
            name='design_idea',
            field=models.TextField(blank=True, help_text='Describe your dream piece or celestial concept'),
        ),
    ]
